version: "3.4"

services:
  database:
    image: postgres:15.2
    container_name: postgres_database_TcaSolutions
    ports:
      - 5432:5432
    restart: "no"
    environment:
      POSTGRES_USER:  tca_solutions
      POSTGRES_PASSWORD:  tca_solutions
      POSTGRES_DB: tca_solutions
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
